version: "3.9"

services:
  homeassistant:
    image: ghcr.io/home-assistant/home-assistant:stable
    container_name: homeassistant
    restart: unless-stopped
    network_mode: host
    environment:
      - TZ=${TZ:-UTC}
    volumes:
      - ./services/homeassistant/config:/config
      - /etc/localtime:/etc/localtime:ro

  pihole:
    image: pihole/pihole:latest
    container_name: pihole
    restart: unless-stopped
    network_mode: host
    environment:
      - TZ=${TZ:-UTC}
      - WEBPASSWORD=${PIHOLE_WEBPASSWORD:-changeme}
      - DNSMASQ_LISTENING=all
      - FTLCONF_REPLY_ADDR4=0.0.0.0
    volumes:
      - ./services/pihole/etc-pihole:/etc/pihole
      - ./services/pihole/etc-dnsmasq.d:/etc/dnsmasq.d
    cap_add:
      - NET_ADMIN
    healthcheck:
      test: ["CMD-SHELL", "pihole -v || exit 1"]
      interval: 1m
      timeout: 10s
      retries: 3

  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared
    restart: unless-stopped
    network_mode: host
    environment:
      - TUNNEL_TOKEN=${CLOUDFLARED_TUNNEL_TOKEN:-}
    command: tunnel --no-autoupdate run
    depends_on:
      - homeassistant
      - n8n
      - pihole

  n8n:
    image: docker.n8n.io/n8nio/n8n:latest
    container_name: n8n
    restart: unless-stopped
    network_mode: host
    environment:
      - TZ=${TZ:-UTC}
      - N8N_SECURE_COOKIE=false
      - GENERIC_TIMEZONE=${TZ:-UTC}
      - N8N_HOST=${N8N_HOST:-localhost}
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
    volumes:
      - ./services/n8n/data:/home/node/.n8n
